baseURL: https://hugo.catcat.blog
defaultContentLanguage: zh-cn
languageCode: zh-CN
timeZone: Asia/Shanghai
title: 猫猫博客
theme: LoveIt

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
hasCJKLanguage: true

author:
  name: sayyiku
  email: sayyikue@gmail.com
  link: https://hugo.catcat.blog

mediaTypes:
  text/plain:
    suffixes: [md]

outputFormats:
  Markdown:
    mediaType: text/plain
    isPlainText: true
    isHTML: false

outputs:
  home: [HTML, RSS, JSON]
  page: [HTML, Markdown]
  section: [HTML, RSS]
  taxonomy: [HTML, RSS]
  taxonomyTerm: [HTML]

privacy:
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
