version: 0.2.X
title: CatCat
description: 猫猫博客
defaultTheme: dark
gitRepo: https://github.com/Sayyiku
fingerprint: sha256
images:
  - https://cdn.lirica.cn/wordpress/2023/03/20230321091445718.webp

app:
  title: Hakula
  themeColor: "#000a12"
  iconColor: "#263238"
  tileColor: "#263238"

search:
  enable: true
  type: algolia
  contentLength: 4000
  maxResultLength: 5
  snippetLength: 50
  highlightTag: em
  algolia:
    index: sakura
    appID: 5UUJIHI5XA
    searchKey: 423d6ba11a00ce805b7d2aa7e2f06ec4

header:
  desktopMode: fixed
  mobileMode: auto
  title:
    name: 猫猫博客

footer:
  enable: true
  hugo: true
  copyright: true
  author: true
  since: 2018
  license: >
    <a
      href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh"
      rel="license external nofollow noopener noreferrer"
      target="_blank"
    >CC BY-NC-SA 4.0</a>

section:
  paginate: 16
  rss: 16

list:
  paginate: 16
  rss: 16

home:
  rss: 10
  profile:
    enable: true
    avatarUrl: https://cdn.lirica.cn/wordpress/2023/02/QQ图片20230125222545.jpg
    title: 猫猫博客
    subtitle: Chaos is a ladder!
    typeit: true
    social: true
  posts:
    enable: true
    paginate: 8

social:
  QQ:
    Weight: -1
    Url: https://cdn.lirica.cn/webp/qq.webp
    Title: QQ
    Newtab: true
    Icon:
      Class: fab fa-qq fa-fw
  GitHub: Sayyiku
  Telegram: yuyulatte
  Bilibili: 267747155
  Email: sayyikue@gmail.com
  RSS: true

page:
  twemoji: false
  lightgallery: true
  ruby: true
  fraction: true
  fontawesome: true
  linkToMarkdown: false
  toc:
    enable: true
    keepStatic: false
    auto: true
  code:
    copy: true
    maxShownLines: 40
  math:
    enable: true
    copyTex: true
  share:
    enable: false
  comment:
    enable: true
    twikoo:
      enable: true
      visitor: true
      envId: https://catcat.blog

typeit:
  duration: 0

cdn:
  data: loli.yml

preconnect:
  - https://hugo.catcat.blog
